config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  post 'sessions/create', to: 'sessions#create', as: 'login'
  get 'sessions/destroy', as: 'logout'

  resources :cheeses
  resources :users
  root 'application#index'
end

app/models/cheese.rb
class Cheese < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :password, :password_confirmation, :on => :create
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :current_user

  def current_user
    if @current_user.nil?
      if session[:user_id].present?
        @current_user = User.find(session[:user_id])
      end
    else
      @current_user
    end
  end

helper_method :current_user

  def authenticate_user!
    if current_user == nil
      redirect_to login_path, alert: 'You must be logged in.'
    end
  end

end

app/controllers/cheeses_controller.rb
class CheesesController < ApplicationController
  before_action :set_cheese, only: [:show, :edit, :update, :destroy]

  def index
    @cheeses = Cheese.all
  end

  def show
  end

  def new
    @cheese = Cheese.new
  end

  def edit
    current_user
  end

  def create
    current_user
    @cheese = Cheese.new(cheese_params)

    respond_to do |format|
      if @cheese.save
        format.html { redirect_to cheeses_path, notice: 'Cheese was successfully created.' }
        format.json { render :show, status: :created, location: @cheese }
      else
        format.html { render :new }
        format.json { render json: @cheese.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cheese.update(cheese_params)
        format.html { redirect_to @cheese, notice: 'Cheese was successfully updated.' }
        format.json { render :show, status: :ok, location: @cheese }
      else
        format.html { render :edit }
        format.json { render json: @cheese.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cheese.destroy
    respond_to do |format|
      format.html { redirect_to cheeses_url, notice: 'Cheese was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_cheese
      @cheese = Cheese.find(params[:id])
    end

    def cheese_params
      params.require(:cheese).permit(:name, :kind, :rating, :description, :pic, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @users = User.find_by_name(params[:name])
    if @users  && @users.authenticate(params[:password])
      session[:user_id] = @users.id
      redirect_to root_path, notice: 'Success'
    else
      flash[:alert] = 'Email or password did not match'
      redirect_to new_user_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :fav_cheese)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheeses_helper.rb
module CheesesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cheeses/_form.html.erb
<%= form_for(@cheese) do |f| %>
  <% if @cheese.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cheese.errors.count, "error") %> prohibited this cheese from being saved:</h2>

      <ul>
      <% @cheese.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="center">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :kind %><br>
      <%= f.text_field :kind %>
    </div>
    <div class="field">
      <%= f.label :rating %><br>
      <%= f.number_field :rating %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :pic %><br>
      <%= f.text_field :pic %>
    </div>
    <div class="field">
      <%= f.label :user_id %><br>
      <%= f.text_field :user_id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/cheeses/edit.html.erb
<h1>Editing Cheese</h1>

<%= render 'form' %>

<%= link_to 'Show', @cheese %> |
<%= link_to 'Back', cheeses_path %>

app/views/cheeses/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Cheeses</h2>
<section class="panel panel-default">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Kind</th>
        <th>Rating (1-5 Cheese Wheels)</th>
        <th>Description</th>
        <th>Pic</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cheeses.each do |cheese| %>
        <tr>
          <td><%= link_to cheese.name, cheese_path(cheese.id) %></td>
          <td><%= cheese.kind %></td>
          <td><% (cheese.rating).times do %>
            <%= image_tag("http://hydra-media.cursecdn.com/skyrim.gamepedia.com/thumb/a/a1/GoatCheeseWheel.png/40px-GoatCheeseWheel.png?version=ff504420ac516527e586c333a7c270f8") %>
            <% end %>
          </td>
          <td><%= cheese.description %></td>
          <td><%= image_tag(cheese.pic, size: '80x50')%></td>
          <td><%= cheese.user %></td>
          <td><%= link_to 'Edit', edit_cheese_path(cheese) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>
<br>

<%= link_to 'New Cheese', new_cheese_path %>

app/views/cheeses/new.html.erb
<h2 class="center">Submit a Cheese</h2>

<%= render 'form' %>

<%= link_to 'Back', cheeses_path %>

app/views/cheeses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cheese.name %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @cheese.kind %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @cheese.rating %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cheese.description %>
</p>

<p>
  <strong>Pic:</strong>
  <%= @cheese.pic %>
</p>

<p>
  <strong>User:</strong>
  <%= @cheese.user %>
</p>
<%= link_to 'Destroy', cheese, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Edit', edit_cheese_path(@cheese) %> |
<%= link_to 'Back', cheeses_path %>

app/views/layouts/_signin.html.erb
<% form_tag("/sessions/create", method: "post") do %>
  <%= label_tag(:name) %>
  <%= text_field_tag(:name) %>
  <%= label_tag(:password) %>
  <%= password_field_tag(:password) %>
  <%= submit_tag("Login") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheeseReact</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
  <div class="container">
    <nav class='row'>
      <%= react_component('Navigation') %>
    </nav>
    <div class="session-box">
      <% if session[:user_id] %>
        <%= link_to 'Logout', logout_path %>
      <% else %>
        <%= form_tag("/sessions/create", method: "post") do %>
          <%= label_tag(:name) %>
          <%= text_field_tag(:name) %>
          <%= label_tag(:password) %>
          <%= password_field_tag(:password) %>
          <%= submit_tag("Login") %>
        <% end %>
      <% end %>
    </div>
  </div>
</header>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<div class="center">
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :Favorite_Cheese %><br>
      <%= f.text_field :fav_cheese %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="center">New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Favorite Cheese:</strong>
  <%= @user.fav_cheese %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>